create table if not exists private.client_secrets (
  client_id text primary key references public.clients(id) on delete cascade,
  meta_access_token text not null default '',
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

create table if not exists private.client_secret_access_log (
  id bigint generated by default as identity primary key,
  client_id text not null references public.clients(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  action text not null check (action in ('revealed', 'updated')),
  created_at timestamptz not null default now()
);

create index if not exists client_secret_access_log_client_created_idx
  on private.client_secret_access_log (client_id, created_at desc);

create index if not exists client_secret_access_log_actor_created_idx
  on private.client_secret_access_log (actor_id, created_at desc);

insert into private.client_secrets (client_id, meta_access_token)
select
  id,
  btrim(regexp_replace(meta_pixel_id, '^.*access[[:space:]]*token[[:space:]]*[-:]*[[:space:]]*', '', 'i'))
from public.clients
where meta_pixel_id ~* 'access[[:space:]]*token'
  and char_length(btrim(regexp_replace(meta_pixel_id, '^.*access[[:space:]]*token[[:space:]]*[-:]*[[:space:]]*', '', 'i'))) > 0
on conflict (client_id) do update
set meta_access_token = excluded.meta_access_token,
    updated_at = now();

update public.clients
set meta_pixel_id = btrim(regexp_replace(meta_pixel_id, '[[:space:]]*\|[[:space:]]*access[[:space:]]*token.*$', '', 'i')),
    updated_at = now()
where meta_pixel_id ~* 'access[[:space:]]*token';

create or replace function public.reveal_client_meta_token(p_client_id text)
returns text
language plpgsql
security definer
set search_path = ''
as $function$
declare
  allowed boolean;
  result_token text;
begin
  select p.active and (
    p.role = 'superadmin'
    or coalesce((p.permissions ->> 'sensitive_credentials_view')::boolean, false)
  )
  into allowed
  from public.profiles p
  where p.id = (select auth.uid());

  if not coalesce(allowed, false) then
    raise exception 'You do not have permission to view sensitive credentials';
  end if;

  select s.meta_access_token into result_token
  from private.client_secrets s
  where s.client_id = p_client_id;

  insert into private.client_secret_access_log (client_id, actor_id, action)
  values (p_client_id, (select auth.uid()), 'revealed');

  return coalesce(result_token, '');
end;
$function$;

create or replace function public.save_client_meta_token(p_client_id text, p_token text)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  allowed boolean;
begin
  select p.active and p.role = 'superadmin'
  into allowed
  from public.profiles p
  where p.id = (select auth.uid());

  if not coalesce(allowed, false) then
    raise exception 'Only Superadmin can update sensitive credentials';
  end if;

  if nullif(btrim(p_token), '') is null then
    raise exception 'Access token cannot be empty';
  end if;

  insert into private.client_secrets (client_id, meta_access_token, updated_at, updated_by)
  values (p_client_id, btrim(p_token), now(), (select auth.uid()))
  on conflict (client_id) do update
  set meta_access_token = excluded.meta_access_token,
      updated_at = excluded.updated_at,
      updated_by = excluded.updated_by;

  insert into private.client_secret_access_log (client_id, actor_id, action)
  values (p_client_id, (select auth.uid()), 'updated');
end;
$function$;

revoke all on function public.reveal_client_meta_token(text) from public, anon;
revoke all on function public.save_client_meta_token(text, text) from public, anon;
grant execute on function public.reveal_client_meta_token(text) to authenticated;
grant execute on function public.save_client_meta_token(text, text) to authenticated;

revoke all on table private.client_secrets from public, anon, authenticated;
revoke all on table private.client_secret_access_log from public, anon, authenticated;
