create table if not exists public.time_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  eod_report_id bigint references public.eod_reports(id) on delete set null,
  work_date date not null,
  hours numeric(5,2) not null check (hours > 0 and hours <= 24),
  memo text not null check (char_length(btrim(memo)) between 1 and 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.time_entries enable row level security;
revoke all on public.time_entries from anon, authenticated;
grant select, insert, update, delete on public.time_entries to authenticated;
grant usage, select on sequence public.time_entries_id_seq to authenticated;

create policy "Users read own time; operations admins read all"
on public.time_entries for select to authenticated
using (user_id = (select auth.uid()) or (select private.has_permission('operations_admin')));

create policy "Users create own time"
on public.time_entries for insert to authenticated
with check (user_id = (select auth.uid()) and (select private.has_permission('eod_reports')));

create policy "Users update own time"
on public.time_entries for update to authenticated
using (user_id = (select auth.uid()) and (select private.has_permission('eod_reports')))
with check (user_id = (select auth.uid()) and (select private.has_permission('eod_reports')));

create policy "Users delete own time"
on public.time_entries for delete to authenticated
using (user_id = (select auth.uid()) and (select private.has_permission('eod_reports')));

create index if not exists time_entries_user_work_date_idx
  on public.time_entries(user_id, work_date desc);
create index if not exists time_entries_report_idx
  on public.time_entries(eod_report_id)
  where eod_report_id is not null;

create table if not exists public.note_reads (
  note_id bigint not null references public.notes(id) on delete cascade,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  seen_at timestamptz not null default now(),
  visible_until timestamptz not null default (now() + interval '24 hours'),
  primary key (note_id, user_id),
  check (visible_until >= seen_at)
);

alter table public.note_reads enable row level security;
revoke all on public.note_reads from anon, authenticated;
grant select, insert, update on public.note_reads to authenticated;

create policy "Users read own note receipts"
on public.note_reads for select to authenticated
using (user_id = (select auth.uid()));

create policy "Users create own note receipts"
on public.note_reads for insert to authenticated
with check (user_id = (select auth.uid()) and (select private.current_app_role()) is not null);

create policy "Users refresh own note receipts"
on public.note_reads for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create index if not exists note_reads_user_visible_idx
  on public.note_reads(user_id, visible_until desc);

alter table public.notes
  add column if not exists task_id text references public.tasks(id) on delete set null,
  add column if not exists converted_at timestamptz,
  add column if not exists converted_by uuid references public.profiles(id) on delete set null;

create index if not exists notes_task_id_idx on public.notes(task_id)
  where task_id is not null;
create index if not exists notes_converted_by_idx on public.notes(converted_by)
  where converted_by is not null;

drop policy if exists "Operations admin converts notes" on public.notes;
create policy "Operations admin converts notes"
on public.notes for update to authenticated
using ((select private.has_permission('operations_admin')))
with check ((select private.has_permission('operations_admin')));

create table if not exists public.ad_performance_reports (
  id bigint generated by default as identity primary key,
  client_id text not null references public.clients(id) on delete cascade,
  report_date date not null default current_date,
  period_start date not null,
  period_end date not null,
  report_status text not null default 'Activa'
    check (report_status in ('Activa', 'Requiere atención', 'Pausada')),
  spend numeric(12,2) not null default 0 check (spend >= 0),
  impressions integer not null default 0 check (impressions >= 0),
  reach integer not null default 0 check (reach >= 0),
  clicks integer not null default 0 check (clicks >= 0),
  ctr numeric(8,2) not null default 0 check (ctr >= 0),
  cpc numeric(12,2) not null default 0 check (cpc >= 0),
  leads integer not null default 0 check (leads >= 0),
  cpl numeric(12,2) not null default 0 check (cpl >= 0),
  appointments integer not null default 0 check (appointments >= 0),
  cost_per_appointment numeric(12,2) not null default 0 check (cost_per_appointment >= 0),
  summary text not null default '' check (char_length(summary) <= 5000),
  wins text not null default '' check (char_length(wins) <= 5000),
  issues text not null default '' check (char_length(issues) <= 5000),
  next_steps text not null default '' check (char_length(next_steps) <= 5000),
  created_by uuid not null default auth.uid() references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, report_date),
  check (period_end >= period_start)
);

alter table public.ad_performance_reports enable row level security;
revoke all on public.ad_performance_reports from anon, authenticated;
grant select, insert, update, delete on public.ad_performance_reports to authenticated;
grant usage, select on sequence public.ad_performance_reports_id_seq to authenticated;

create policy "Active users read ADS reports"
on public.ad_performance_reports for select to authenticated
using ((select private.current_app_role()) is not null);

create policy "Client editors create ADS reports"
on public.ad_performance_reports for insert to authenticated
with check (created_by = (select auth.uid()) and (select private.has_permission('clients_edit')));

create policy "Authors or operations admins update ADS reports"
on public.ad_performance_reports for update to authenticated
using ((created_by = (select auth.uid()) or (select private.has_permission('operations_admin'))) and (select private.has_permission('clients_edit')))
with check ((created_by = (select auth.uid()) or (select private.has_permission('operations_admin'))) and (select private.has_permission('clients_edit')));

create policy "Operations admins delete ADS reports"
on public.ad_performance_reports for delete to authenticated
using ((select private.has_permission('operations_admin')));

create index if not exists ad_reports_client_date_idx
  on public.ad_performance_reports(client_id, report_date desc);
create index if not exists ad_reports_author_date_idx
  on public.ad_performance_reports(created_by, report_date desc);

create or replace function private.validate_ads_report_client_status()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not exists (
    select 1 from public.clients
    where id = new.client_id and status in ('ADS LIVE', 'ADS PAUSED')
  ) then
    raise exception 'ADS reports are available only after a campaign is active';
  end if;
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.validate_ads_report_client_status() from public, anon, authenticated;
drop trigger if exists validate_ads_report_client_status on public.ad_performance_reports;
create trigger validate_ads_report_client_status
before insert or update on public.ad_performance_reports
for each row execute function private.validate_ads_report_client_status();

comment on table public.time_entries is 'Manual Upwork-style time entries included in daily EOD and weekly reports.';
comment on table public.note_reads is 'Per-user communication receipts; cards remain active for 24 hours after being seen.';
comment on table public.ad_performance_reports is 'Dated client-facing Meta Ads performance reports with author attribution.';
