alter table public.profiles
  add column if not exists email text,
  add column if not exists active boolean not null default true,
  add column if not exists permissions jsonb not null default '{}'::jsonb;

update public.profiles p
set email = u.email
from auth.users u
where u.id = p.id and p.email is null;

update public.profiles
set permissions = case role
  when 'superadmin' then '{"clients_create":true,"clients_edit":true,"tasks_create":true,"calendar_manage":true,"eod_reports":true,"users_manage":true}'::jsonb
  when 'onboarding_media' then '{"clients_create":true,"clients_edit":true,"tasks_create":false,"calendar_manage":true,"eod_reports":true,"users_manage":false}'::jsonb
  else '{"clients_create":false,"clients_edit":true,"tasks_create":false,"calendar_manage":true,"eod_reports":true,"users_manage":false}'::jsonb
end
where permissions = '{}'::jsonb;

create or replace function private.has_permission(permission_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select role = 'superadmin' or coalesce((permissions ->> permission_name)::boolean, false)
     from public.profiles
     where id = (select auth.uid()) and active),
    false
  );
$$;

revoke all on function private.has_permission(text) from public, anon;
grant execute on function private.has_permission(text) to authenticated;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, permissions)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    '{"clients_create":true,"clients_edit":true,"tasks_create":false,"calendar_manage":true,"eod_reports":true,"users_manage":false}'::jsonb
  );
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

drop policy if exists "Team updates clients" on public.clients;
create policy "Permitted team updates clients" on public.clients
  for update to authenticated
  using ((select private.has_permission('clients_edit')))
  with check ((select private.has_permission('clients_edit')));

drop policy if exists "Kevin and Diego create clients" on public.clients;
create policy "Permitted team creates clients" on public.clients
  for insert to authenticated
  with check ((select private.has_permission('clients_create')));

alter table public.clients
  add column if not exists kyc_status text not null default 'Pending',
  add column if not exists project_type text not null default 'Pending',
  add column if not exists ideal_customer_profile text not null default '',
  add column if not exists available_assets text not null default '',
  add column if not exists google_docs_url text not null default '',
  add column if not exists facebook_page_url text not null default '',
  add column if not exists instagram_url text not null default '',
  add column if not exists meta_business_portfolio_id text not null default '',
  add column if not exists meta_ad_account_id text not null default '',
  add column if not exists meta_pixel_id text not null default '',
  add column if not exists landing_page_url text not null default '',
  add column if not exists onboarding_completed boolean not null default false,
  add column if not exists ghl_access_confirmed boolean not null default false,
  add column if not exists facebook_access_confirmed boolean not null default false,
  add column if not exists ad_account_access_confirmed boolean not null default false,
  add column if not exists pixel_access_confirmed boolean not null default false,
  add column if not exists domain_access_confirmed boolean not null default false,
  add column if not exists payment_method_confirmed boolean not null default false,
  add column if not exists kyc_completed boolean not null default false,
  add column if not exists a2p_submitted boolean not null default false,
  add column if not exists funnel_live boolean not null default false,
  add column if not exists meta_campaign_live boolean not null default false,
  add column if not exists dossier_copied_at timestamptz,
  add column if not exists dossier_copied_by uuid references public.profiles(id) on delete set null,
  add column if not exists google_docs_updated_at timestamptz,
  add column if not exists google_docs_updated_by uuid references public.profiles(id) on delete set null;

create table if not exists public.client_dossier_events (
  id bigint generated by default as identity primary key,
  client_id text not null references public.clients(id) on delete cascade,
  actor_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  action text not null check (action in ('copied_google_docs', 'downloaded_pdf', 'marked_google_docs_updated')),
  created_at timestamptz not null default now()
);

alter table public.client_dossier_events enable row level security;
revoke all on public.client_dossier_events from anon, authenticated;
grant select, insert on public.client_dossier_events to authenticated;
grant usage, select on sequence public.client_dossier_events_id_seq to authenticated;

create policy "Team reads dossier events" on public.client_dossier_events
  for select to authenticated
  using ((select private.current_app_role()) is not null);
create policy "Team records own dossier events" on public.client_dossier_events
  for insert to authenticated
  with check (actor_id = (select auth.uid()));

create index if not exists client_dossier_events_client_created_idx
  on public.client_dossier_events (client_id, created_at desc);

alter table public.tasks add column if not exists completed_at timestamptz;

create or replace function private.set_task_timestamps()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  if new.status = 'Completada' and old.status is distinct from 'Completada' then
    new.completed_at = now();
  elsif new.status <> 'Completada' then
    new.completed_at = null;
  end if;
  return new;
end;
$$;

revoke all on function private.set_task_timestamps() from public, anon, authenticated;
drop trigger if exists tasks_set_timestamps on public.tasks;
create trigger tasks_set_timestamps before update on public.tasks
  for each row execute function private.set_task_timestamps();

update public.tasks set completed_at = updated_at where status = 'Completada' and completed_at is null;
create index if not exists tasks_owner_completed_at_idx on public.tasks (owner_role, completed_at desc);

create table if not exists public.eod_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  report_date date not null default current_date,
  completed_tasks jsonb not null default '[]'::jsonb,
  manual_tasks jsonb not null default '[]'::jsonb,
  notes text not null default '' check (char_length(notes) <= 5000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, report_date)
);

alter table public.eod_reports enable row level security;
revoke all on public.eod_reports from anon, authenticated;
grant select, insert, update on public.eod_reports to authenticated;
grant usage, select on sequence public.eod_reports_id_seq to authenticated;

create policy "Users read own EOD; superadmin reads all" on public.eod_reports
  for select to authenticated
  using (user_id = (select auth.uid()) or (select private.is_superadmin()));
create policy "Users create own EOD" on public.eod_reports
  for insert to authenticated
  with check (user_id = (select auth.uid()) and (select private.has_permission('eod_reports')));
create policy "Users update own EOD" on public.eod_reports
  for update to authenticated
  using (user_id = (select auth.uid()) and (select private.has_permission('eod_reports')))
  with check (user_id = (select auth.uid()) and (select private.has_permission('eod_reports')));

create index if not exists eod_reports_date_user_idx on public.eod_reports (report_date desc, user_id);

create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  client_id text references public.clients(id) on delete set null,
  title text not null check (char_length(btrim(title)) between 1 and 160),
  event_type text not null default 'Evento' check (event_type in ('Evento', 'Reunión', 'Nota')),
  start_at timestamptz not null,
  end_at timestamptz,
  meeting_url text not null default '',
  notes text not null default '' check (char_length(notes) <= 5000),
  reminder_minutes integer[] not null default '{15}'::integer[]
    check (reminder_minutes <@ array[15,60,1440]::integer[]),
  created_by uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_at is null or end_at >= start_at)
);

alter table public.calendar_events enable row level security;
revoke all on public.calendar_events from anon, authenticated;
grant select, insert, update, delete on public.calendar_events to authenticated;
grant usage, select on sequence public.calendar_events_id_seq to authenticated;

create policy "Team reads calendar" on public.calendar_events
  for select to authenticated using ((select private.current_app_role()) is not null);
create policy "Permitted team creates calendar events" on public.calendar_events
  for insert to authenticated
  with check (created_by = (select auth.uid()) and (select private.has_permission('calendar_manage')));
create policy "Creator or superadmin updates calendar events" on public.calendar_events
  for update to authenticated
  using (created_by = (select auth.uid()) or (select private.is_superadmin()))
  with check ((created_by = (select auth.uid()) or (select private.is_superadmin())) and (select private.has_permission('calendar_manage')));
create policy "Creator or superadmin deletes calendar events" on public.calendar_events
  for delete to authenticated
  using (created_by = (select auth.uid()) or (select private.is_superadmin()));

create index if not exists calendar_events_start_idx on public.calendar_events (start_at);
create index if not exists calendar_events_client_start_idx on public.calendar_events (client_id, start_at);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null default '',
  source_type text not null,
  source_id text not null,
  notify_at timestamptz not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (recipient_id, source_type, source_id, notify_at)
);

alter table public.notifications enable row level security;
revoke all on public.notifications from anon, authenticated;
grant select, update (read_at) on public.notifications to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

create policy "Users read own notifications" on public.notifications
  for select to authenticated using (recipient_id = (select auth.uid()));
create policy "Users mark own notifications read" on public.notifications
  for update to authenticated
  using (recipient_id = (select auth.uid()))
  with check (recipient_id = (select auth.uid()));

create index if not exists notifications_recipient_due_idx
  on public.notifications (recipient_id, notify_at desc) where read_at is null;

create or replace function private.schedule_calendar_notifications()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  reminder integer;
  member record;
begin
  if tg_op = 'UPDATE' then
    delete from public.notifications
    where source_type = 'calendar_event' and source_id = new.id::text and read_at is null;
  end if;

  foreach reminder in array new.reminder_minutes loop
    for member in select id from public.profiles where active loop
      insert into public.notifications (recipient_id, title, body, source_type, source_id, notify_at)
      values (
        member.id,
        case new.event_type when 'Reunión' then 'Próxima reunión' else 'Próximo evento' end,
        new.title,
        'calendar_event',
        new.id::text,
        new.start_at - make_interval(mins => reminder)
      )
      on conflict do nothing;
    end loop;
  end loop;
  return new;
end;
$$;

revoke all on function private.schedule_calendar_notifications() from public, anon, authenticated;
drop trigger if exists calendar_event_notifications on public.calendar_events;
create trigger calendar_event_notifications after insert or update on public.calendar_events
  for each row execute function private.schedule_calendar_notifications();

drop trigger if exists capture_calendar_activity on public.calendar_events;
create trigger capture_calendar_activity after insert or update or delete on public.calendar_events
  for each row execute function private.capture_operational_activity();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'calendar_events'
  ) then
    alter publication supabase_realtime add table public.calendar_events;
  end if;
end
$$;

grant select (id, email, full_name, avatar_url, role, active, permissions, created_at, updated_at, last_task_seen_at)
  on public.profiles to authenticated;

