alter table public.profiles
  add column if not exists last_task_seen_at timestamptz not null default now();

grant update (last_task_seen_at) on public.profiles to authenticated;

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  client_id text references public.clients(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 160),
  body text not null default '' check (char_length(body) <= 5000),
  created_by uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.notes enable row level security;
grant select, insert, update, delete on public.notes to authenticated;
grant usage, select on sequence public.notes_id_seq to authenticated;

drop policy if exists "Team reads notes" on public.notes;
create policy "Team reads notes" on public.notes
  for select to authenticated
  using ((select auth.uid()) is not null);

drop policy if exists "Superadmin creates notes" on public.notes;
create policy "Superadmin creates notes" on public.notes
  for insert to authenticated
  with check ((select private.is_superadmin()) and created_by = (select auth.uid()));

drop policy if exists "Superadmin updates notes" on public.notes;
create policy "Superadmin updates notes" on public.notes
  for update to authenticated
  using ((select private.is_superadmin()) and created_by = (select auth.uid()))
  with check ((select private.is_superadmin()) and created_by = (select auth.uid()));

drop policy if exists "Superadmin deletes notes" on public.notes;
create policy "Superadmin deletes notes" on public.notes
  for delete to authenticated
  using ((select private.is_superadmin()));

create index if not exists notes_client_created_at_idx on public.notes (client_id, created_at desc);
create index if not exists notes_created_by_idx on public.notes (created_by);
create index if not exists tasks_owner_role_created_at_idx on public.tasks (owner_role, created_at desc);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tasks'
  ) then
    alter publication supabase_realtime add table public.tasks;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notes'
  ) then
    alter publication supabase_realtime add table public.notes;
  end if;
end
$$;
