alter table public.clients
  add column if not exists assigned_role text not null default 'onboarding_media'
    check (assigned_role in ('onboarding_media', 'automation_funnels', 'superadmin'));

alter table public.tasks alter column client_id drop not null;
alter table public.tasks add column if not exists due_at date;
alter table public.tasks add column if not exists created_by uuid references public.profiles(id) on delete set null default auth.uid();
alter table public.tasks add column if not exists comments text not null default '';
alter table public.tasks drop constraint if exists tasks_priority_check;
alter table public.tasks add constraint tasks_priority_check
  check (priority in ('Urgente', 'Alta', 'Media', 'Baja'));

create table if not exists public.client_workflow_steps (
  id bigint generated by default as identity primary key,
  client_id text not null references public.clients(id) on delete cascade,
  step_key text not null,
  title text not null,
  owner_role text not null check (owner_role in ('superadmin', 'onboarding_media', 'automation_funnels')),
  owner_name text not null,
  sort_order integer not null,
  completed boolean not null default false,
  notes text not null default '',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (client_id, step_key)
);

create table if not exists public.client_audit_log (
  id bigint generated by default as identity primary key,
  client_id text not null references public.clients(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default 'Sistema',
  actor_role text not null default 'system',
  action text not null,
  changed_fields text[] not null default '{}',
  summary text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  client_id text references public.clients(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text not null default 'Sistema',
  actor_role text not null default 'system',
  entity_type text not null,
  entity_id text,
  action text not null,
  old_values jsonb,
  new_values jsonb,
  created_at timestamptz not null default now()
);

alter table public.activity_log enable row level security;
revoke all on public.activity_log from anon;
grant select on public.activity_log to authenticated;
grant usage, select on sequence public.activity_log_id_seq to authenticated;

drop policy if exists "Team reads activity" on public.activity_log;
create policy "Team reads activity" on public.activity_log
  for select to authenticated
  using ((select private.current_app_role()) is not null);

drop policy if exists "Team creates clients" on public.clients;
create policy "Kevin and Diego create clients" on public.clients
  for insert to authenticated
  with check ((select private.current_app_role()) in ('superadmin', 'onboarding_media'));

drop policy if exists "Role creates own tasks" on public.tasks;
create policy "Role creates own tasks" on public.tasks
  for insert to authenticated
  with check (
    ((select private.is_superadmin()) or owner_role = (select private.current_app_role()))
    and (created_by is null or created_by = (select auth.uid()))
  );

create or replace function private.capture_operational_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_name text := 'Sistema';
  v_actor_role text := 'system';
  v_client_id text;
  v_entity_id text;
begin
  select coalesce(full_name, 'Usuario'), role into v_actor_name, v_actor_role
  from public.profiles where id = (select auth.uid());

  if tg_table_name = 'clients' then
    v_entity_id := coalesce(new.id, old.id);
    v_client_id := case when tg_op = 'DELETE' then null else new.id end;
  else
    v_client_id := coalesce(new.client_id, old.client_id);
    v_entity_id := coalesce(new.id::text, old.id::text);
  end if;

  insert into public.activity_log
    (client_id, actor_id, actor_name, actor_role, entity_type, entity_id, action, old_values, new_values)
  values
    (v_client_id, (select auth.uid()), coalesce(v_actor_name, 'Sistema'), coalesce(v_actor_role, 'system'),
     tg_table_name, v_entity_id, lower(tg_op),
     case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
     case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end);

  return coalesce(new, old);
end;
$$;

revoke all on function private.capture_operational_activity() from public, anon, authenticated;

drop trigger if exists capture_clients_activity on public.clients;
create trigger capture_clients_activity after insert or update or delete on public.clients
  for each row execute function private.capture_operational_activity();
drop trigger if exists capture_tasks_activity on public.tasks;
create trigger capture_tasks_activity after insert or update or delete on public.tasks
  for each row execute function private.capture_operational_activity();
drop trigger if exists capture_blockers_activity on public.blockers;
create trigger capture_blockers_activity after insert or update or delete on public.blockers
  for each row execute function private.capture_operational_activity();
drop trigger if exists capture_notes_activity on public.notes;
create trigger capture_notes_activity after insert or update or delete on public.notes
  for each row execute function private.capture_operational_activity();
drop trigger if exists capture_workflow_activity on public.client_workflow_steps;
create trigger capture_workflow_activity after insert or update or delete on public.client_workflow_steps
  for each row execute function private.capture_operational_activity();

create index if not exists clients_assigned_role_idx on public.clients (assigned_role);
create index if not exists tasks_due_at_status_idx on public.tasks (due_at, status);
create index if not exists tasks_created_by_idx on public.tasks (created_by);
create index if not exists client_audit_log_actor_id_idx on public.client_audit_log (actor_id);
create index if not exists activity_log_client_created_idx on public.activity_log (client_id, created_at desc);
create index if not exists activity_log_actor_created_idx on public.activity_log (actor_id, created_at desc);
