alter table public.clients
  add column if not exists ads_pause_reason text not null default '',
  add column if not exists ads_paused_at timestamptz,
  add column if not exists ads_paused_by uuid references public.profiles(id) on delete set null;

alter table public.clients drop constraint if exists clients_status_check;
alter table public.clients add constraint clients_status_check
  check (status in ('ONBOARDING', 'A2P SUBMITTED', 'ADS LIVE', 'ADS PAUSED'));

alter table public.clients drop constraint if exists clients_ads_pause_reason_check;
alter table public.clients add constraint clients_ads_pause_reason_check
  check (
    char_length(ads_pause_reason) <= 2000
    and (status <> 'ADS PAUSED' or char_length(btrim(ads_pause_reason)) > 0)
  );

create table if not exists public.client_ad_status_events (
  id bigint generated by default as identity primary key,
  client_id text not null references public.clients(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text not null default 'Sistema',
  actor_role text not null default 'system',
  event_type text not null check (event_type in ('paused', 'resumed')),
  previous_status text not null,
  new_status text not null,
  note text not null default '' check (char_length(note) <= 2000),
  created_at timestamptz not null default now()
);

alter table public.client_ad_status_events enable row level security;
revoke all on public.client_ad_status_events from anon, authenticated;
grant select on public.client_ad_status_events to authenticated;

drop policy if exists "Active team reads client ADS status events" on public.client_ad_status_events;
create policy "Active team reads client ADS status events" on public.client_ad_status_events
  for select to authenticated
  using ((select private.current_app_role()) is not null);

create index if not exists client_ad_status_events_client_created_idx
  on public.client_ad_status_events (client_id, created_at desc);
create index if not exists clients_ads_paused_by_idx
  on public.clients (ads_paused_by);

create or replace function private.prepare_client_ads_status_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status is distinct from old.status and new.status = 'ADS PAUSED' then
    if old.status <> 'ADS LIVE' then
      raise exception 'Only ADS LIVE clients can be paused';
    end if;
    if nullif(btrim(new.ads_pause_reason), '') is null then
      raise exception 'A pause reason is required';
    end if;
    new.ads_pause_reason = btrim(new.ads_pause_reason);
    new.ads_paused_at = now();
    new.ads_paused_by = (select auth.uid());
    new.meta_campaign_live = false;
    new.meta_status = 'Paused';
  elsif new.status is distinct from old.status and old.status = 'ADS PAUSED' and new.status = 'ADS LIVE' then
    new.meta_campaign_live = true;
    new.meta_status = 'Active';
  end if;
  return new;
end;
$$;

revoke all on function private.prepare_client_ads_status_change() from public, anon, authenticated;

drop trigger if exists prepare_client_ads_status_change on public.clients;
create trigger prepare_client_ads_status_change
  before update on public.clients
  for each row execute function private.prepare_client_ads_status_change();

create or replace function private.capture_client_ads_status_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_name text := 'Sistema';
  v_actor_role text := 'system';
  v_event_type text;
  v_note text;
begin
  if new.status is not distinct from old.status then
    return new;
  end if;

  if new.status = 'ADS PAUSED' then
    v_event_type := 'paused';
    v_note := new.ads_pause_reason;
  elsif old.status = 'ADS PAUSED' and new.status = 'ADS LIVE' then
    v_event_type := 'resumed';
    v_note := 'Campaña reactivada';
  else
    return new;
  end if;

  select coalesce(full_name, 'Usuario'), role
  into v_actor_name, v_actor_role
  from public.profiles
  where id = (select auth.uid());

  insert into public.client_ad_status_events
    (client_id, actor_id, actor_name, actor_role, event_type, previous_status, new_status, note)
  values
    (new.id, (select auth.uid()), coalesce(v_actor_name, 'Sistema'), coalesce(v_actor_role, 'system'),
     v_event_type, old.status, new.status, v_note);

  return new;
end;
$$;

revoke all on function private.capture_client_ads_status_event() from public, anon, authenticated;

drop trigger if exists capture_client_ads_status_event on public.clients;
create trigger capture_client_ads_status_event
  after update on public.clients
  for each row execute function private.capture_client_ads_status_event();
