-- Phase 3: configurable User Admin role, training hub, intake confirmation,
-- time zones, and strict EOD rules.

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check
  check (role in ('onboarding_media', 'automation_funnels', 'user_admin', 'superadmin'));

alter table public.clients drop constraint if exists clients_assigned_role_check;
alter table public.clients add constraint clients_assigned_role_check
  check (assigned_role in ('onboarding_media', 'automation_funnels', 'user_admin', 'superadmin'));

alter table public.tasks drop constraint if exists tasks_owner_role_check;
alter table public.tasks add constraint tasks_owner_role_check
  check (owner_role in ('onboarding_media', 'automation_funnels', 'user_admin', 'superadmin'));

alter table public.client_workflow_steps drop constraint if exists client_workflow_steps_owner_role_check;
alter table public.client_workflow_steps add constraint client_workflow_steps_owner_role_check
  check (owner_role in ('onboarding_media', 'automation_funnels', 'user_admin', 'superadmin'));

alter table public.profiles
  add column if not exists timezone text not null default 'America/Managua'
    check (char_length(timezone) between 3 and 80);

update public.profiles set timezone = case
  when lower(coalesce(full_name, '')) = 'daniel' then 'Africa/Lagos'
  when lower(coalesce(full_name, '')) = 'kevin' then 'America/New_York'
  else 'America/Managua'
end;

alter table public.clients
  add column if not exists timezone text not null default 'America/New_York'
    check (char_length(timezone) between 3 and 80),
  add column if not exists intake_form_completed boolean not null default false,
  add column if not exists intake_form_completed_at timestamptz,
  add column if not exists intake_form_completed_by uuid references public.profiles(id) on delete set null;

alter table public.calendar_events
  add column if not exists timezone text not null default 'America/New_York'
    check (char_length(timezone) between 3 and 80);

-- Superadmins can review EOD reports, but cannot create an EOD for themselves.
drop policy if exists "Users create own EOD" on public.eod_reports;
create policy "Non-admin users create own EOD" on public.eod_reports
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and (select private.current_app_role()) <> 'superadmin'
    and (select private.has_permission('eod_reports'))
  );

drop policy if exists "Users update own EOD" on public.eod_reports;
create policy "Non-admin users update own EOD" on public.eod_reports
  for update to authenticated
  using (
    user_id = (select auth.uid())
    and (select private.current_app_role()) <> 'superadmin'
    and (select private.has_permission('eod_reports'))
  )
  with check (
    user_id = (select auth.uid())
    and (select private.current_app_role()) <> 'superadmin'
    and (select private.has_permission('eod_reports'))
  );

create table if not exists public.training_modules (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 1 and 180),
  description text not null default '',
  drive_url text not null default '',
  audience_role text,
  sort_order integer not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (audience_role is null or audience_role in ('onboarding_media', 'automation_funnels', 'user_admin', 'superadmin'))
);

create table if not exists public.training_items (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.training_modules(id) on delete cascade,
  title text not null check (char_length(btrim(title)) between 1 and 240),
  description text not null default '',
  drive_url text not null default '',
  resource_type text not null default 'Lección'
    check (resource_type in ('Lección', 'Documento', 'Video', 'Carpeta')),
  sort_order integer not null,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  unique (module_id, sort_order)
);

create table if not exists public.training_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id bigint not null references public.training_items(id) on delete cascade,
  completed_at timestamptz not null default now(),
  notes text not null default '' check (char_length(notes) <= 1000),
  primary key (user_id, item_id)
);

alter table public.training_modules enable row level security;
alter table public.training_items enable row level security;
alter table public.training_progress enable row level security;

revoke all on public.training_modules, public.training_items, public.training_progress from anon, authenticated;
grant select on public.training_modules, public.training_items to authenticated;
grant select, insert, update, delete on public.training_progress to authenticated;
grant usage, select on sequence public.training_modules_id_seq, public.training_items_id_seq to authenticated;

create policy "Active team reads training modules" on public.training_modules
  for select to authenticated
  using (active and (select private.current_app_role()) is not null);

create policy "Active team reads training items" on public.training_items
  for select to authenticated
  using (
    (select private.current_app_role()) is not null
    and exists (select 1 from public.training_modules m where m.id = module_id and m.active)
  );

create policy "Users read own training progress; superadmin reads all" on public.training_progress
  for select to authenticated
  using (
    (select private.current_app_role()) is not null
    and (user_id = (select auth.uid()) or (select private.is_superadmin()))
  );

create policy "Users mark own training progress" on public.training_progress
  for insert to authenticated
  with check (user_id = (select auth.uid()) and (select private.current_app_role()) is not null);

create policy "Users update own training progress" on public.training_progress
  for update to authenticated
  using (user_id = (select auth.uid()) and (select private.current_app_role()) is not null)
  with check (user_id = (select auth.uid()) and (select private.current_app_role()) is not null);

create policy "Users clear own training progress" on public.training_progress
  for delete to authenticated
  using (user_id = (select auth.uid()) and (select private.current_app_role()) is not null);

create index if not exists training_items_module_order_idx on public.training_items (module_id, sort_order);
create index if not exists training_progress_item_idx on public.training_progress (item_id);

insert into public.training_modules (title, description, drive_url, audience_role, sort_order) values
  ('Empieza aquí — Cultura, reglas y objetivo', 'Visión, reglas no negociables, seguridad de cuentas y check-in diario.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', null, 0),
  ('Module 1: Agency Foundation & Core Offer', 'Modelo de negocio, mercado objetivo y garantía.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', null, 1),
  ('Module 2: Operational Culture, Speed & Asset Efficiency', 'Velocidad, comunicación y uso responsable de herramientas.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', null, 2),
  ('Module 3: Post-Sale & Client Onboarding', 'Onboarding, activos, pagos y accesos de Meta.', 'https://drive.google.com/drive/folders/1JDH612D_P2TFoc4VbZ0t-p3E55gTq3Z6?usp=drive_link', 'onboarding_media', 3),
  ('Module 4: Technical Sub-Account & Infrastructure Build', 'Subcuentas, A2P, workflows, Make y Retell.', 'https://drive.google.com/drive/folders/1JDH612D_P2TFoc4VbZ0t-p3E55gTq3Z6?usp=drive_link', 'automation_funnels', 4),
  ('Module 5: Funnel Customization & Custom Styling', 'Activos, conexiones, CSS y pruebas del funnel.', 'https://drive.google.com/drive/folders/1ee2DCiYCzG_eAhAvOm8lxxLMbwd4a91p?usp=sharing', 'automation_funnels', 5),
  ('Module 6: Ad Creative Production, Launch & Audits', 'Creativos, configuración, lanzamiento y auditoría de campañas.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', 'onboarding_media', 6)
on conflict (sort_order) do update set
  title = excluded.title, description = excluded.description, drive_url = excluded.drive_url,
  audience_role = excluded.audience_role, active = true, updated_at = now();

with lessons(module_order, item_order, title, description, link, resource_type) as (values
  (0, 1, 'Visión, meta y KPI de la agencia', '12–20 citas agendadas por mes, servicio rápido, exacto y transparente.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', 'Documento'),
  (0, 2, 'Reglas no negociables y seguridad de cuentas', 'No falsificar métricas, respetar límites de cuentas y no desperdiciar créditos.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', 'Documento'),
  (0, 3, 'Responsabilidades de Diego y Daniel', 'Handoff, comunicación y alcance operativo de cada rol.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', 'Documento'),
  (0, 4, 'EOD diario y revisión semanal del Training Hub', 'Enviar el reporte antes de cerrar el día y revisar el hub al menos una vez por semana.', 'https://docs.google.com/document/d/1mcrrNiZAF6yf6Pi6jT7hummCISrELEdI-mGYGeDq6yQ/edit?usp=sharing', 'Documento'),
  (1, 1, 'Lesson 1.1 — Core Business Model & Value Proposition', '', '', 'Lección'),
  (1, 2, 'Lesson 1.2 — Target Market & High-Ticket Guarantee', '', '', 'Lección'),
  (2, 1, 'Lesson 2.1 — Work Ethic & Speed-to-Lead', '', '', 'Lección'),
  (2, 2, 'Lesson 2.2 — Communication Protocols', 'WhatsApp, GHL Conversations y Slack.', '', 'Lección'),
  (2, 3, 'Lesson 2.3 — Software Credit Efficiency & Asset Management', '', '', 'Lección'),
  (3, 1, 'Lesson 3.1 — Live Onboarding Call', 'Guion y protocolo de pantalla compartida de 30–60 minutos.', '', 'Lección'),
  (3, 2, 'Lesson 3.2 — GHL Re-Billing & Meta Payment', '', '', 'Lección'),
  (3, 3, 'Lesson 3.3 — Asset Collection & Client Folder', 'EIN, datos, logos, medios, GHL y carpeta de cliente.', 'https://drive.google.com/drive/folders/1JDH612D_P2TFoc4VbZ0t-p3E55gTq3Z6?usp=drive_link', 'Carpeta'),
  (3, 4, 'Lesson 3.4 — Meta Access Handoff', 'Partner permissions, Page, Ad Account y Pixel.', '', 'Lección'),
  (4, 1, 'Lesson 4.1 — Sub-Account & Master Snapshot', '', '', 'Lección'),
  (4, 2, 'Lesson 4.2 — Domain, SSL & Calendar', '', '', 'Lección'),
  (4, 3, 'Lesson 4.3 — Big 5 Workflows', 'Despliegue y pruebas.', '', 'Lección'),
  (4, 4, 'Lesson 4.4 — Make.com Scenarios & Webhooks', '', '', 'Lección'),
  (4, 5, 'Lesson 4.5 — Retell AI Agent & Call Flow', '', '', 'Lección'),
  (4, 6, 'Lesson 4.6 — A2P 10DLC & Weekly Submissions', 'Páginas dummy, branding y 1–3 envíos proactivos por semana.', 'https://drive.google.com/drive/folders/1JDH612D_P2TFoc4VbZ0t-p3E55gTq3Z6?usp=drive_link', 'Carpeta'),
  (5, 1, 'Lesson 5.1 — GHL Media Folder & Connections', 'Google, Facebook, Instagram, Reviews y Applications.', 'https://drive.google.com/drive/folders/1ee2DCiYCzG_eAhAvOm8lxxLMbwd4a91p?usp=sharing', 'Carpeta'),
  (5, 2, 'Lesson 5.2 — Gemini for Custom Funnel CSS', '', '', 'Lección'),
  (5, 3, 'Lesson 5.3 — CSS Injection & Live Testing', '', '', 'Lección'),
  (6, 1, 'Lesson 6.1 — Ad Angles, Voiceovers & AI Creative', '', '', 'Lección'),
  (6, 2, 'Lesson 6.2 — Static Image Variations', 'Lovart AI y HighLevel Ask AI.', '', 'Lección'),
  (6, 3, 'Lesson 6.3 — CapCut Rapid Editing', 'Límite operativo de 45 minutos.', '', 'Lección'),
  (6, 4, 'Lesson 6.4 — Meta Ads, UTM, Pixel & Launch', 'Configuración, evento Lead y check-in diario.', '', 'Lección'),
  (6, 5, 'Lesson 6.5 — Campaign Optimization & Audits', 'Regla de 4 días sin cambios y aprobación antes del lanzamiento.', '', 'Lección')
)
insert into public.training_items (module_id, sort_order, title, description, drive_url, resource_type)
select m.id, l.item_order, l.title, l.description, l.link, l.resource_type
from lessons l join public.training_modules m on m.sort_order = l.module_order
on conflict (module_id, sort_order) do update set
  title = excluded.title, description = excluded.description,
  drive_url = excluded.drive_url, resource_type = excluded.resource_type;
